server:
  port: 80

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_db
    username: audi
    password: audi0530!
  jpa:
    show-sql: true
    hibernate.ddl-auto: none
    properties:
      hibernate:
        format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  mail:
    host: smtp.gmail.com
    port: 587
    username: pseudo.audi@gmail.com
    password: pseudo0530!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  file:
    name: /Users/2918924/toy-project/audi/log
  logback:
      max-history: 9999
      max-file-size: 10MB
  level:
    com.pseudonym.audi : error
    com.pseudonym.audi.controller : debug

jwt:
  secret: "secretKey"
  expireTime: 604800000


