spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: pseudo.audi@gmail.com
    password: pseudo0530!
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true